package:
  name: webgeocalc
  version: "{{ environ.get('TRAVIS_TAG', 'dev').lstrip('v') }}"

source:
  git_url: ../

build:
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -v "

requirements:
  build:
    - pip
    - python
    - pbr
  run:
    - python
    - requests
    - pbr

test:
  imports:
    - webgeocalc

about:
  home: https://github.com/seignovert/python-webgeocalc
  license: MIT
  license_family: MIT
  summary: Python package for NAIF WebGeoCalc API
  description: |
    In december 2018, JPL/NAIF announced an experimental
    API RESTful interface for their new WebGeoCalc server
    (which make online SPICE calculations).
    This package is an early attempt to provide a Python
    interface to make SPICE calculation through this API.
  doc_url: https://webgeocalc.readthedocs.io/

extra:
  recipe-maintainers:
    - seignovert
