language: python
cache: pip

python: 3.6

env:
  - JOB="tests"
  - JOB="docs"
  - JOB="linter"

install:
  - pip install tox-travis
script:
  - tox

deploy:
  - provider: pypi
    user: seignovert
    password:
      secure: RnvVK0k/25wCMAx/3B0umMm3F/jMTU+LQ7phFlt8fpvjP4EvZ0nxHcf7++RM8fQpWcLneY6MneLh1yZoKlkL9QadjEC9zqvqp+12hJqPrfpqhQmKE8kiuAiVZ3/uJJa6SVPNxVDHYQ0w4TUe4KYzNWQVOyXkt4tbtX60DKgKCWVWSnCFqCHNtdPrgaYoMDm+Koq0fHOLMHU4K64rWk10eo3O1w2QHmurYqxvcDwup7t7T2MKgkjfEu5iCsS5VvQTNlRCE86gxSha2xiJcU1MSx1+hGHxadPlPFuPAZVGgGyj3tplJkjvUfnaxoZedHJ5HPvmrlmFvexstXi8tOubkn2ognPf4VOrTKxnqAdYCkiLs/RARe6e3krVxgwGRbV3LsPR4YH6fSnrLvA73oDEHicumZdFIrZXe4PrXi41XMELqkMPHX/S3BbizNKbzXZzryVEXdCIP5zKywDzBfMbCgX9WrIag6QWDvUtBqfK9Z70ICqlGLlogTLEHdsyAGaRzOJYRn7SQ0VyETVE/Z53b0WbRbuDYrmDUWOZoGAIv96YgurfWwBQbpMAN5z1qMGXfAI2qj22NUzoJzbJoWrd1L0EaR/Ohe6SQHpddR+O6GNJ/tM4/6w/cWdpivhJ/K/6A2EGrsd7lddrzMRKs3DlKEX+6ul2BmHDD35ZRNupXH0=
    skip_cleanup: true
    distributions: sdist bdist_wheel
    on:
      tags: true
      condition: $JOB = "tests"

  - provider: releases
    name: Version $TRAVIS_TAG
    api_key:
      secure: NoqdiA4+taRIbHQ1/tlPAhA298Sbasqch8M0OnlStAl9Mn76Xksjw8r7ltpp24k0Tb+esgRp9JgAVJzUnPdOdszTuKK6dEO0LNF3EIwqPfyaE1RNkZ9El0dDoh2SZy4GOZNZcQlyNIuVP9t9p4RbH1URpaUOi1gGypwYqI3o0Xqk3Pac81sguszxOdHiYDHD0CajFrasmmsmj7Rrbl1YTm1m4aArqUBU0sXUUEuuxqd6bDGACwyCE91Nsoq8+ar12/BdMcHSzt0UDzlM9qeBM+MSSiIwbq52wwZ+/c67wL5ZuRc5kydqeqEmMta5lLHZpDItdzI1ACzsXXrqOqa4FypOAPEuBqfRcGyBk3ESVHuywf92ESpeAGi8pGQInsT4xQGxpDirNc8QnBThkjS6CS4xGmOl3EnokY3WPsFdklVL8+CYkWDcU0yFszr5AiUSTHTi4TLYF5ef5Y69YK0z24C4+Zg+49Q2oIkqf4RGoA3mObLt18euzOax63iCr6GU47RfCldsyb1+jvnYue4dnJ51UfzeoZU8hYhc3e8If3iA9o9s+yGULBQ/m+HDEfSTWeYlpigYQahG8r+d+sIkDhx1D2q7sFx5iEW3Mjmi7uADJWxsymCIoz09k3NVgq700il5drnEXAZ0PKHwgZuWjTrbjo6bhlfrvIvAxAAEO4Q=
    skip-cleanup: true
    on:
      tags: true
      condition: $JOB = "docs"
